insert into `users` (`email`, `login_type`, `nick_name`, `password`, `phone_number`, `second_password`, `user_status`)
values
    ('test1@test.com', 'BASIC', 'test1','{noop}1111!', '010-1234-1231', '1234', 'TUTEE'),
    ('test2@test.com', 'BASIC', 'test2','{noop}1111!', '010-1234-1232', '1234', 'TUTEE'),
    ('test3@test.com', 'BASIC', 'test3','{noop}1111!', '010-1234-1233', '1234', 'TUTEE'),
    ('test4@test.com', 'BASIC', 'test4','{noop}1111!', '010-1234-1234', '1234', 'TUTEE'),
    ('test5@test.com', 'BASIC', 'test5','{noop}1111!', '010-1234-1235', '1234', 'TUTEE'),
    ('test6@test.com', 'BASIC', 'test6','{noop}1111!', '010-1234-1236', '1234', 'TUTEE'),
    ('test7@test.com', 'BASIC', 'test7','{noop}1111!', '010-1234-1237', '1234', 'TUTEE'),
    ('test8@test.com', 'BASIC', 'test8','{noop}1111!', '010-1234-1238', '1234', 'TUTEE'),
    ('test9@test.com', 'BASIC', 'test9','{noop}1111!', '010-1235-1239', '1234', 'NONE'),
    ('test10@test.com', 'BASIC', 'test10','{noop}1111!', '010-1231-1234', '1234', 'TUTOR'),
    ('test11@test.com', 'BASIC', 'test11','{noop}1111!', '010-1232-1234', '1234', 'TUTOR'),
    ('test12@test.com', 'BASIC', 'test12','{noop}1111!', '010-1233-1234', '1234', 'TUTOR'),
    ('test13@test.com', 'BASIC', 'test13','{noop}1111!', '010-1236-1234', '1234', 'TUTOR'),
    ('test14@test.com', 'BASIC', 'test14','{noop}1111!', '010-1237-1234', '1234', 'TUTOR'),
    ('test15@test.com', 'BASIC', 'test15','{noop}1111!', '010-1238-1234', '1234', 'TUTOR'),
    ('test16@test.com', 'BASIC', 'test16','{noop}1111!', '010-1239-1234', '1234', 'TUTOR')
;

insert into `profile_image` (`file_name`, `url`)
values
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png'),
    ('basic','https://image-test-suyoung.s3.ap-northeast-2.amazonaws.com/image/user.png')
;

insert into `profile` (`bio`, `character`, `difference`, `gender`, `name`, `pay`, `pre_tutoring`, `profile_status`, `rate`, `school`, `subject_string`, `want_date`, `wanted_status`, `way`, `profile_image_profile_image_id`, `user_user_id`)
values
    ('수학 갈아드립니다', '소심함', null, '남', '김수학', '시간당 20마넌', '가능합니다', 'TUTEE', 0.0, '제주대 철학과 19학번',
     '수학,영어,과학', '암때나 가능', 'REQUEST', '알아서 합니다', 1, 10),
    ('자격증 썰어주세요', '소심함', null, '남', '김수학', '시간당 20마넌', '가능합니다', 'TUTEE', 0.0, '제주대 철학과 19학번',
     '수학,영어,과학,자격증', '암때나 가능', 'REQUEST', '알아서 합니다', 2, 1),
    ('수학 갈아주세요', '까칠함', null, '남', '갈갈이', '시간당 만원에 구합니다', '해주세요ㅛㅗㅗ', 'TUTEE', 0.0, '고구려대 곤충산업과 20학번',
     '수학,과학', '암때나 해주세요', 'REQUEST', '알아서 해주세요', 3, 1),
    ('과학 갈아주세요', '까칠함', null, '남', '갈갈이', '시간당 만원에 구합니다', '해주세요ㅛㅗㅗ', 'TUTEE', 0.0, '나사렛대 수어통역학과 17학번',
     '수학,영어', '암때나 해주세요', 'REQUEST', '알아서 해주세요', 4, 1),
    ('영어 토할거같아요', '까칠함', null, '남', '제이팍', '시간당 만원에 구합니다', '해주세요ㅛㅗㅗ', 'TUTEE', 0.0, '뉴욕대학교 국문학과 20학번',
     '수학,영어', '암때나 해주세요', 'REQUEST', '알아서 해주세요', 5, 1),
    ('자격증 썰어주세요', '소심함', null, '남', '김수학', '시간당 20마넌', '가능합니다', 'TUTEE', 0.0, '삼각산고 2학년',
     '수학,영어,과학,자격증', '암때나 가능', 'REQUEST', '알아서 합니다', 6, 2),
    ('수학 갈아주세요', '까칠함', null, '남', '수포자', '시간당 만원에 구합니다', '해주세요ㅛㅗㅗ', 'TUTEE', 0.0, '압구정고 1학년',
     '수학,과학', '암때나 해주세요', 'REQUEST', '알아서 해주세요', 7, 2),
    ('과학 알려줘', '까칠함', null, '남', '과포자', '시간당 만원에 구합니다', '해주세요ㅛㅗㅗ', 'TUTEE', 0.0, '오류고등학교 3학년',
     '수학,영어', '암때나 해주세요', 'REQUEST', '알아서 해주세요', 8, 2),
    ('영어 토할거같아요', '까칠함', null, '남', '제이팍', '시간당 만원에 구합니다', '해주세요ㅛㅗㅗ', 'TUTEE', 0.0, '영등포공업고 1학년',
     '수학,영어', '암때나 해주세요', 'REQUEST', '알아서 해주세요', 9, 2),
    ('자격증 썰어주세요', '소심함', null, '남', '김수학', '시간당 20마넌', '가능합니다', 'TUTEE', 0.0, '서울공업고 3학년',
     '수학,영어,과학,자격증', '암때나 가능', 'REQUEST', '알아서 합니다', 10, 3),
    ('국어 훈민정음', '까칠함', null, '남', '한국사', '시간당 만원에 구합니다', '해주세요ㅛㅗㅗ', 'TUTEE', 0.0, '서울 디자인고등학교 1학년',
     '수학,과학,국어', '암때나 해주세요', 'REQUEST', '알아서 해주세요', 11, 3),
    ('사회 이다지쌤 찾습니다', '까칠함', null, '남', '사탐신', '시간당 만원에 구합니다', '해주세요ㅛㅗㅗ', 'TUTEE', 0.0, '세종과학고 3학년',
     '사회', '암때나 해주세요', 'REQUEST', '알아서 해주세요', 12, 3),
    ('영어 1타만', '까칠함', null, '남', '제이팍', '시간당 만원에 구합니다', '해주세요ㅛㅗㅗ', 'TUTEE', 0.0, '반포고 2학년',
     '수학,영어', '암때나 해주세요', 'REQUEST', '알아서 해주세요', 13, 3),
    ('자격증 썰어주세요', '소심함', null, '남', '김수학', '시간당 20마넌', '가능합니다', 'TUTEE', 0.0, '마포고등학교 3학년',
     '수학,영어,과학,자격증', '암때나 가능', 'REQUEST', '알아서 합니다', 14, 4),
    ('수학 대치동이 좋나요', '까칠함', null, '남', '피타고라스', '시간당 만원에 구합니다', '해주세요ㅛㅗㅗ', 'TUTEE', 0.0, '이화여자고 2학년',
     '수학,과학', '암때나 해주세요', 'REQUEST', '알아서 해주세요', 15, 4),
    ('기타 ㄱㄱㄱ', '까칠함', null, '남', '기타남', '시간당 만원에 구합니다', '해주세요ㅛㅗㅗ', 'TUTEE', 0.0, '보성여자고등학교 3학년',
     '수학,영어,기타', '암때나 해주세요', 'REQUEST', '알아서 해주세요', 16, 4),
    ('영어 토할거같아요', '까칠함', null, '남', '다니엘', '시간당 만원에 구합니다', '해주세요ㅛㅗㅗ', 'TUTEE', 0.0, '노원고 2학년',
     '수학,영어', '암때나 해주세요', 'REQUEST', '알아서 해주세요', 17, 4),
    ('자격증 썰어주세요', '소심함', null, '남', '자격증 컬렉터', '시간당 20마넌', '가능합니다', 'TUTEE', 0.0, '강서고 3학년',
     '수학,영어,과학,자격증', '암때나 가능', 'REQUEST', '알아서 합니다', 18, 5),
    ('수학 갈아주세요', '까칠함', null, '남', '더이상없다', '시간당 만원에 구합니다', '해주세요ㅛㅗㅗ', 'TUTEE', 0.0, '가락고 2학년',
     '수학,과학', '암때나 해주세요', 'REQUEST', '알아서 해주세요', 19, 5),
    ('과학 하고싶어요', '까칠함', null, '남', '사이언티스트', '시간당 만원에 구합니다', '해주세요ㅛㅗㅗ', 'TUTEE', 0.0, '고려대 부속고등학교 3학년',
     '수학,영어', '암때나 해주세요', 'REQUEST', '알아서 해주세요', 20, 5),
    ('영어 토할거같아요', '까칠함', null, '남', '핸리', '시간당 만원에 구합니다', '해주세요ㅛㅗㅗ', 'TUTEE', 0.0, '구로 고등학교 2학년',
     '수학,영어', '암때나 해주세요', 'REQUEST', '알아서 해주세요', 21, 5),
    ('자격증 썰어주세요', '소심함', null, '남', '기사자격증', '시간당 20마넌', '가능합니다', 'TUTEE', 0.0, '풍문고 3학년',
     '수학,영어,과학,자격증', '암때나 가능', 'REQUEST', '알아서 합니다', 22, 6),
    ('수학 갈아주세요', '까칠함', null, '남', '우영우', '시간당 만원에 구합니다', '해주세요ㅛㅗㅗ', 'TUTEE', 0.0, '한강미디어고 2학년',
     '수학,과학', '암때나 해주세요', 'REQUEST', '알아서 해주세요', 23, 6),
    ('과학 갈아주세요', '까칠함', null, '남', '권모술수', '시간당 만원에 구합니다', '해주세요ㅛㅗㅗ', 'TUTEE', 0.0, '홍익디자인고 3학년',
     '수학,영어', '암때나 해주세요', 'REQUEST', '알아서 해주세요', 24, 6),
    ('영어 토할거같아요', '까칠함', null, '남', '합격하자', '시간당 만원에 구합니다', '해주세요ㅛㅗㅗ', 'TUTEE', 0.0, '창문여고 2학년',
     '수학,영어', '암때나 해주세요', 'REQUEST', '알아서 해주세요', 25, 6),
    ('자격증 썰어주세요', '소심함', null, '남', '수능 3일', '시간당 20마넌', '가능합니다', 'TUTEE', 0.0, '장충고 2학년',
     '수학,영어,과학,자격증', '암때나 가능', 'REQUEST', '알아서 합니다', 26, 7),
    ('수학 갈아주세요', '까칠함', null, '남', '수학영재', '시간당 만원에 구합니다', '해주세요ㅛㅗㅗ', 'TUTEE', 0.0, '인창고 2학년',
     '수학,과학', '암때나 해주세요', 'REQUEST', '알아서 해주세요', 27, 7),
    ('과학 화학 배워 폭탄만들고 싶다', 'ISFJ', null, '남', '화학으로폭탄제조', '시간당 만원에 구합니다', '해주세요ㅛㅗㅗ', 'TUTEE', 0.0, '경남고 2학년',
     '수학,영어', '암때나 해주세요', 'REQUEST', '알아서 해주세요', 28, 7),
    ('영어 토할거같아요', 'ISTP', null, '남', '세종대왕', '시간당 만원에 구합니다', '해주세요ㅛㅗㅗ', 'TUTEE', 0.0, '영신고 1학년',
     '수학,영어', '암때나 해주세요', 'REQUEST', '알아서 해주세요', 29, 7),
    ('자격증 없어요', 'ESFP', null, '남', '더이상진짜없다', '시간당 20마넌', '가능합니다', 'TUTEE', 0.0, '월계고 3학년',
     '수학,영어,과학,자격증', '암때나 가능', 'REQUEST', '알아서 합니다', 30, 8),
    ('과학 살려주세욧', 'INTP', null, '남', '살려줘', '시간당 만원에 구합니다', '해주세요ㅛㅗㅗ', 'TUTEE', 0.0, '태릉고 2학년',
     '수학,영어', '암때나 해주세요', 'REQUEST', '알아서 해주세요', 31, 8),
    ('영어 토할거같아요', 'ENFP', null, '남', '유학중', '시간당 만원에 구합니다', '해주세요ㅛㅗㅗ', 'TUTEE', 0.0, '서울예고 2학년',
     '수학,영어', '암때나 해주세요', 'REQUEST', '알아서 해주세요', 32, 8),
    ('수학 갈아봐요', '소심함', '갈아드릴수 있습니다', '남', '김수학', '시간당 20마넌', '가능합니다', 'TUTOR', 4.5, '제주대 철학과 19학번',
     '수학,영어,과학', '암때나 가능', 'NONE', '알아서 합니다', 33, 10),
    ('수학 갈아봐요', '소심함', '갈아드릴수 있습니다', '남', '김과학', '시간당 20마넌', '가능합니다', 'TUTOR', 4.5, '제주대 철학과 19학번',
     '수학,영어,과학', '암때나 가능', 'NONE', '알아서 합니다', 34, 10),
    ('수학 갈아봐요', '소심함', '갈아드릴수 있습니다', '남', '갑니다', '시간당 20마넌', '가능합니다', 'TUTOR', 4.5, '제주대 철학과 19학번',
     '수학,영어,과학', '암때나 가능', 'NONE', '알아서 합니다', 35, 10),
    ('수학 갈아봐요', '소심함', '갈아드릴수 있습니다', '남', '김수학', '시간당 20마넌', '가능합니다', 'TUTOR', 4.5, '제주대 철학과 19학번',
     '수학,영어,과학', '암때나 가능', 'NONE', '알아서 합니다', 36, 10),
    ('자격증 갈아드릴게요', '소심함', '알아서 잘해드립니다', '남', '김수학', '시간당 20마넌', '가능합니다', 'TUTOR', 5.0, '제주대 철학과 19학번',
     '수학,영어,과학,자격증', '암때나 가능', 'REQUEST', '알아서 합니다', 37, 11),
    ('수학 알려줌미다', 'ENFJ', '차이점이 없어요', '남', '제이팍', '시간당 20마넌', '해주세요ㅛㅗㅗ', 'TUTOR', 4.5, '고구려대 곤충산업과 20학번',
     '수학,과학', '암때나 해주세요', 'REQUEST', '알아서 해주세요', 38, 11),
    ('과학 살려줍니다', 'INFP', '그냥 해볼게요', '남', '우영우', '시간당 20마넌', '해주세요ㅛㅗㅗ', 'TUTOR', 3.5, '나사렛대 수어통역학과 17학번',
     '수학,영어', '암때나 해주세요', 'REQUEST', '알아서 해주세요', 39, 11),
    ('영어 나도 토할거같아요', 'ENFP', '할수이싿!!', '남', '제이팍', '시간당 20마넌', '해주세요ㅛㅗㅗ', 'TUTOR', 2.5, '뉴욕대학교 국문학과 20학번',
     '수학,영어', '암때나 해주세요', 'REQUEST', '알아서 해주세요', 40, 11),
    ('자격증 갈아드릴게요', '소심함', '알아서 잘해드립니다', '남', '김수학', '시간당 20마넌', '가능합니다', 'TUTOR', 5.0, '제주대 철학과 19학번',
     '수학,영어,과학,자격증', '암때나 가능', 'REQUEST', '알아서 합니다', 41, 12),
    ('수학 알려줌미다', '까칠함', '차이점이 없어요', '남', '황과외', '시간당 20마넌', '해주세요ㅛㅗㅗ', 'TUTOR', 4.5, '고구려대 곤충산업과 20학번',
     '사회,과학', '암때나 해주세요', 'REQUEST', '알아서 해주세요', 42, 12),
    ('과학 살려줍니다', '까칠함', '그냥 해볼게요', '남', '한국사', '시간당 20마넌', '해주세요ㅛㅗㅗ', 'TUTOR', 3.5, '나사렛대 수어통역학과 17학번',
     '수학,사회', '암때나 해주세요', 'REQUEST', '알아서 해주세요', 43, 12),
    ('영어 나도 토할거같아요', '까칠함', '할수이싿!!', '남', '제이팍', '시간당 20마넌', '해주세요ㅛㅗㅗ', 'TUTOR', 2.5, '뉴욕대학교 국문학과 20학번',
     '수학,사회', '암때나 해주세요', 'REQUEST', '알아서 해주세요', 45, 12),
    ('자격증 갈아드릴게요', '소심함', '알아서 잘해드립니다', '남', '김수학', '시간당 20마넌', '가능합니다', 'TUTOR', 5.0, '제주대 철학과 19학번',
     '수학,영어,과학,자격증', '암때나 가능', 'REQUEST', '알아서 합니다', 46, 13),
    ('수학 알려줌미다', '까칠함', '차이점이 없어요', '남', '깃헙', '시간당 20마넌', '해주세요ㅛㅗㅗ', 'TUTOR', 4.5, '고구려대 곤충산업과 20학번',
     '수학,과학', '암때나 해주세요', 'REQUEST', '알아서 해주세요', 47, 13),
    ('국어 살려줍니다', '까칠함', '그냥 해볼게요', '남', '김코딩', '시간당 20마넌', '해주세요ㅛㅗㅗ', 'TUTOR', 3.5, '나사렛대 수어통역학과 17학번',
     '국어,수학,자격증', '암때나 해주세요', 'REQUEST', '알아서 해주세요', 48, 13),
    ('영어 나도 토할거같아요', '까칠함', '할수이싿!!', '남', '제이팍', '시간당 20마넌', '해주세요ㅛㅗㅗ', 'TUTOR', 2.5, '뉴욕대학교 국문학과 20학번',
     '기타,영어', '암때나 해주세요', 'REQUEST', '알아서 해주세요', 49, 13),
    ('자격증 갈아드릴게요', '소심함', '알아서 잘해드립니다', '남', '김수학', '시간당 20마넌', '가능합니다', 'TUTOR', 5.0, '제주대 철학과 19학번',
     '수학,영어,과학,자격증', '암때나 가능', 'REQUEST', '알아서 합니다', 50, 14),
    ('사회 알려줌미다', '까칠함', '차이점이 없어요', '남', 'HTML', '시간당 20마넌', '해주세요ㅛㅗㅗ', 'TUTOR', 4.5, '고구려대 곤충산업과 20학번',
     '수학,과학,사회', '암때나 해주세요', 'REQUEST', '알아서 해주세요', 51, 14),
    ('과학 살려줍니다', '까칠함', '그냥 해볼게요', '남', '걍하자', '시간당 20마넌', '해주세요ㅛㅗㅗ', 'TUTOR', 3.5, '나사렛대 수어통역학과 17학번',
     '수학,영어,자격증', '암때나 해주세요', 'REQUEST', '알아서 해주세요', 52, 14),
    ('영어 나도 토할거같아요', '까칠함', '할수이싿!!', '남', '믿고따라와', '시간당 20마넌', '해주세요ㅛㅗㅗ', 'TUTOR', 2.5, '뉴욕대학교 국문학과 20학번',
     '수학,영어', '암때나 해주세요', 'REQUEST', '알아서 해주세요', 53, 14),
    ('자격증 갈아드릴게요', '소심함', '알아서 잘해드립니다', '남', '김수학', '시간당 20마넌', '가능합니다', 'TUTOR', 5.0, '제주대 철학과 19학번',
     '수학,영어,과학,자격증', '암때나 가능', 'REQUEST', '알아서 합니다', 54, 15),
    ('수학 알려줌미다', '까칠함', '차이점이 없어요', '남', '이름이없다', '시간당 20마넌', '해주세요ㅛㅗㅗ', 'TUTOR', 4.5, '고구려대 곤충산업과 20학번',
     '수학,과학', '암때나 해주세요', 'REQUEST', '알아서 해주세요', 55, 15),
    ('과학 살려줍니다', '까칠함', '그냥 해볼게요', '남', '익명', '시간당 20마넌', '해주세요ㅛㅗㅗ', 'TUTOR', 3.5, '나사렛대 수어통역학과 17학번',
     '수학,영어', '암때나 해주세요', 'REQUEST', '알아서 해주세요', 56, 15),
    ('영어 나도 토할거같아요', '까칠함', '할수이싿!!', '남', '권모술수', '시간당 20마넌', '해주세요ㅛㅗㅗ', 'TUTOR', 2.5, '뉴욕대학교 국문학과 20학번',
     '국어,영어', '암때나 해주세요', 'REQUEST', '알아서 해주세요', 57, 15),
    ('자격증 갈아드릴게요', '소심함', '알아서 잘해드립니다', '남', '아무렇게', '시간당 6마넌ㅍㅍㅍㅍ', '가능합니다', 'TUTOR', 5.0, '제주대 철학과 19학번',
     '수학,영어,과학,자격증', '암때나 가능', 'REQUEST', '알아서 합니다', 58, 16),
    ('수학 알려줌미다', 'ESTP', '차이점이 없어요', '남', '걍ㄱㄱ', '하루당 20마넌ㅍㅍㅍㅍ', '해주세요ㅛㅗㅗ', 'TUTOR', 4.5, '고구려대 곤충산업과 20학번',
     '사회,과학', '암때나 해주세요', 'REQUEST', '알아서 해주세요', 59, 16),
    ('과학 살려줍니다', 'INTP', '그냥 해볼게요', '남', '김과학', '시간당 25ㅍㅍㅍㅍㅍㅍ', '해주세요ㅛㅗㅗ', 'TUTOR', 3.5, '나사렛대 수어통역학과 17학번',
     '과학,영어', '암때나 해주세요', 'REQUEST', '알아서 해주세요', 60, 16),
    ('영어 나도 토할거같아요', 'ENFP', '할수이싿!!', '남', '제이팍', '시간당 10 ㅍㅍㅍㅍㅍ', '해주세요ㅛㅗㅗ', 'TUTOR', 2.5, '뉴욕대학교 국문학과 20학번',
     '수학,영어', '암때나 해주세요', 'REQUEST', '알아서 해주세요', 20, 16)
;

insert into `subject` (`subject_title`)
values
    ('영어'),
    ('수학'),
    ('국어'),
    ('사회'),
    ('과학'),
    ('자격증'),
    ('기타')
;

insert into `subject_profile` (`content`, `profile_profile_id`, `subject_subject_id`)
values
    ('',1,2),('',1,1),('',1,5),
    ('',2,2),('',2,1),('',2,5),('',2,6),
    ('',3,2),('',3,5),
    ('',4,2),('',4,1),
    ('',5,2),('',5,1),
    ('',6,2),('',6,1),('',6,5),('',6,6),
    ('',7,2),('',7,5),
    ('',8,2),('',8,1),
    ('',9,2),('',9,1),
    ('',10,2),('',10,1),('',10,5),('',10,6),
    ('',11,2),('',11,5),('',11,3),
    ('',12,4),
    ('',13,2),('',13,1),
    ('',14,2),('',14,1),('',14,5),('',14,6),
    ('',15,2),('',15,5),
    ('',16,2),('',16,1),('',16,7),
    ('',17,2),('',17,1),
    ('',18,2),('',18,1),('',18,5),('',18,7),
    ('',19,2),('',19,5),
    ('',20,2),('',20,1),
    ('',21,2),('',21,1),
    ('',22,2),('',22,1),('',22,5),('',22,6),
    ('',23,2),('',23,5),
    ('',24,2),('',24,1),
    ('',25,2),('',25,1),
    ('',26,2),('',26,1),('',26,5),('',26,6),
    ('',27,2),('',27,5),
    ('',28,2),('',28,1),
    ('',29,2),('',29,1),
    ('',30,2),('',30,1),('',30,5),('',30,6),
    ('',31,2),('',31,1),
    ('',32,2),('',32,1),
    ('잘알려드릴게',33,2),('잘알려드릴게',33,1),('잘알려드릴게',33,5),
    ('잘알려드릴게',34,2),('잘알려드릴게',34,1),('잘알려드릴게',34,5),
    ('잘알려드릴게',35,2),('잘알려드릴게',35,1),('잘알려드릴게',35,5),
    ('잘알려드릴게',36,2),('잘알려드릴게',36,1),('잘알려드릴게',36,5),
    ('잘알려드릴게',37,2),('잘알려드릴게',37,1),('잘알려드릴게',37,5),('잘알려드릴게',37,6),
    ('잘알려드릴게',38,2),('잘알려드릴게',38,5),
    ('잘알려드릴게',39,2),('잘알려드릴게',39,1),
    ('잘알려드릴게',40,2),('잘알려드릴게',40,1),
    ('잘알려드릴게',41,2),('잘알려드릴게',41,1),('잘알려드릴게',41,5),('잘알려드릴게',41,6),
    ('잘알려드릴게',42,4),('잘알려드릴게',42,5),
    ('잘알려드릴게',43,2),('잘알려드릴게',43,4),
    ('잘알려드릴게',44,2),('잘알려드릴게',44,4),
    ('잘알려드릴게',45,2),('잘알려드릴게',45,1),('잘알려드릴게',45,5),('잘알려드릴게',45,6),
    ('잘알려드릴게',46,2),('잘알려드릴게',46,5),
    ('잘알려드릴게',47,2),('잘알려드릴게',47,3),('잘알려드릴게',47,6),
    ('잘알려드릴게',48,1),('잘알려드릴게',48,7),
    ('잘알려드릴게',49,2),('잘알려드릴게',49,1),('잘알려드릴게',49,5),('잘알려드릴게',49,6),
    ('잘알려드릴게',50,2),('잘알려드릴게',50,5),('잘알려드릴게',50,4),
    ('잘알려드릴게',51,2),('잘알려드릴게',51,1),('잘알려드릴게',51,6),
    ('잘알려드릴게',52,2),('잘알려드릴게',52,1),
    ('잘알려드릴게',53,2),('잘알려드릴게',53,1),('잘알려드릴게',53,5),('잘알려드릴게',53,6),
    ('잘알려드릴게',54,2),('잘알려드릴게',54,5),
    ('잘알려드릴게',55,2),('잘알려드릴게',55,1),
    ('잘알려드릴게',56,1),('잘알려드릴게',56,3),
    ('잘알려드릴게',57,2),('잘알려드릴게',57,1),('잘알려드릴게',57,5),('잘알려드릴게',57,6),
    ('잘알려드릴게',58,4),('잘알려드릴게',58,5),
    ('잘알려드릴게',59,1),('잘알려드릴게',59,5),
    ('잘알려드릴게',60,1),('잘알려드릴게',60,2)
;
